name = "CluGen"
uuid = "48a2e8d8-1966-47f1-a982-993d59b21037"
authors = ["Nuno Fachada <faken@fakenmc.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
