name: Coverage
on:
  pull_request:
    branches: [main]
    paths: [ 'src/**', 'test/**', '.github/workflows/Coverage.yml' ]
  push:
    branches: [main]
    paths: [ 'src/**', 'test/**', '.github/workflows/Coverage.yml' ]
    tags: '*'
  workflow_dispatch:

jobs:
  test:
    name: Test on Julia LTS and Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1.9
        with:
          version: '1.6'
      - uses: julia-actions/cache@v1.2
      - uses: julia-actions/julia-buildpkg@v1.4
      - uses: julia-actions/julia-runtest@v1.9
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info