name: Tests
on:
  pull_request:
    branches: [main]
    paths: [ 'src/**', 'test/**', '.github/workflows/Tests.yml' ]
  push:
    branches: [main]
    paths: [ 'src/**', 'test/**', '.github/workflows/Tests.yml' ]
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.1', 'nightly']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1.9
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1.2.0
      - uses: julia-actions/julia-buildpkg@v1.4
      - uses: julia-actions/julia-runtest@v1.9
